---
# tasks file for vscode-ansible

- include: osx.yml
  when: ansible_os_family == 'Darwin'

- include: debian.yml
  when: ansible_os_family == 'elementary OS' or ansible_os_family == 'Debian'
    
- name: List Inatalled VSCode extensions
  command: code --list-extensions
  register: installed_extensions
  changed_when: false

- name: Install Required VSCode extensions
  command: "code --install-extension {{ item }}"
  with_items: "{{ extensions }}"
  when: "'{{ item }}' not in installed_extensions.stdout"